# TODO ?????????

server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///Album #?servierTimezone=UTC
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.whh.domain
  mapper-locations: classpath:mapper/*.xml
reggie:
  path: D:\Javaworkplace\Music\music_ssm\target\classes\static\imgs\head
